const PurchaseOrder = require('../models/PurchaseOrder');
const Product = require('../models/Product');
const Supplier = require('../models/Supplier');
const { asyncHandler, sendResponse, getPagination, paginationMeta } = require('../utils/helpers');
const { checkLowStockAndAutoOrder } = require('../utils/scheduler');

// GET /api/orders
const getOrders = asyncHandler(async (req, res) => {
  const { page, limit, skip } = getPagination(req.query);
  const { status, supplierId, isAutoGenerated } = req.query;

  const query = {};
  if (status) query.status = status;
  if (supplierId) query.supplierId = supplierId;
  if (isAutoGenerated !== undefined) query.isAutoGenerated = isAutoGenerated === 'true';

  const [orders, total] = await Promise.all([
    PurchaseOrder.find(query)
      .populate('supplierId', 'name phone email')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit),
    PurchaseOrder.countDocuments(query),
  ]);

  sendResponse(res, 200, { data: orders, pagination: paginationMeta(total, page, limit) });
});

// GET /api/orders/:id
const getOrder = asyncHandler(async (req, res) => {
  const order = await PurchaseOrder.findById(req.params.id)
    .populate('supplierId', 'name phone email address');
  if (!order) return res.status(404).json({ success: false, message: 'Order not found' });
  sendResponse(res, 200, { data: order });
});

// POST /api/orders
const createOrder = asyncHandler(async (req, res) => {
  const { supplierId, items, notes } = req.body;

  const supplier = await Supplier.findOne({ _id: supplierId, isActive: true });
  if (!supplier) return res.status(404).json({ success: false, message: 'Supplier not found' });

  const enrichedItems = [];
  let totalAmount = 0;

  for (const item of items) {
    const product = await Product.findById(item.productId);
    if (!product) {
      return res.status(404).json({ success: false, message: `Product not found: ${item.productId}` });
    }
    const unitPrice = item.unitPrice || product.buyingPrice;
    enrichedItems.push({
      productId: product._id,
      productName: product.name,
      quantity: item.quantity,
      unitPrice,
    });
    totalAmount += item.quantity * unitPrice;
  }

  const order = await PurchaseOrder.create({
    supplierId,
    supplierName: supplier.name,
    items: enrichedItems,
    totalAmount,
    notes,
    isAutoGenerated: false,
  });

  sendResponse(res, 201, { data: order }, 'Purchase order created successfully');
});

// PATCH /api/orders/:id/status
const updateOrderStatus = asyncHandler(async (req, res) => {
  const { status } = req.body;
  const validStatuses = ['pending', 'ordered', 'received', 'cancelled'];

  if (!validStatuses.includes(status)) {
    return res.status(400).json({ success: false, message: `Invalid status. Must be one of: ${validStatuses.join(', ')}` });
  }

  const order = await PurchaseOrder.findById(req.params.id);
  if (!order) return res.status(404).json({ success: false, message: 'Order not found' });

  if (order.status === 'cancelled' || order.status === 'received') {
    return res.status(400).json({ success: false, message: `Cannot update a ${order.status} order` });
  }

  order.status = status;
  await order.save();

  // Restock products when order is marked received
  if (status === 'received') {
    const bulkOps = order.items.map((item) => ({
      updateOne: {
        filter: { _id: item.productId },
        update: { $inc: { quantity: item.quantity }, $set: { lowStockAlertSent: false } },
      },
    }));
    await Product.bulkWrite(bulkOps);
  }

  const populated = await PurchaseOrder.findById(order._id).populate('supplierId', 'name phone');
  sendResponse(res, 200, { data: populated }, `Order status updated to '${status}'`);
});

// DELETE /api/orders/:id
const deleteOrder = asyncHandler(async (req, res) => {
  const order = await PurchaseOrder.findById(req.params.id);
  if (!order) return res.status(404).json({ success: false, message: 'Order not found' });
  if (order.status !== 'pending') {
    return res.status(400).json({ success: false, message: 'Only pending orders can be deleted' });
  }
  await order.deleteOne();
  sendResponse(res, 200, {}, 'Order deleted successfully');
});

// POST /api/orders/trigger-auto-check
const triggerAutoCheck = asyncHandler(async (req, res) => {
  setImmediate(() => checkLowStockAndAutoOrder());
  sendResponse(res, 200, {}, 'Auto-order check triggered. Processing in background.');
});

module.exports = { getOrders, getOrder, createOrder, updateOrderStatus, deleteOrder, triggerAutoCheck };