const cron = require('node-cron');
const Product = require('../models/Product');
const Supplier = require('../models/Supplier');
const PurchaseOrder = require('../models/PurchaseOrder');
const { sendLowStockAlert, sendExpiryAlert, sendAutoOrderEmail } = require('./emailService');

// ─── Low Stock Check & Auto Order ────────────────────────────────────────────

const checkLowStockAndAutoOrder = async () => {
  console.log(`[${new Date().toISOString()}] Running low stock check...`);
  try {
    // Find all low stock products where alert hasn't been sent yet
    const lowStockProducts = await Product.find({
      isActive: true,
      $expr: { $lte: ['$quantity', '$minStockLevel'] },
    }).populate('supplierId');

    if (!lowStockProducts.length) {
      console.log('✅ No low stock products found.');
      return;
    }

    console.log(`⚠️  Found ${lowStockProducts.length} low stock product(s).`);

    // 1. Send low stock alert email (for products where alert wasn't already sent)
    const newAlerts = lowStockProducts.filter((p) => !p.lowStockAlertSent);
    if (newAlerts.length > 0) {
      try {
        await sendLowStockAlert(newAlerts);
        console.log(`📧 Low stock alert sent for ${newAlerts.length} product(s).`);

        // Mark alert as sent
        await Product.updateMany(
          { _id: { $in: newAlerts.map((p) => p._id) } },
          { lowStockAlertSent: true }
        );
      } catch (emailErr) {
        console.error('Failed to send low stock email:', emailErr.message);
      }
    }

    // 2. Auto-generate purchase orders for trusted suppliers with auto-order enabled
    const supplierProductMap = new Map();

    for (const product of lowStockProducts) {
      if (!product.supplierId) continue;
      const supplier = product.supplierId;

      if (!supplier.isTrusted || !supplier.autoOrderEnabled) continue;

      // Avoid duplicate pending orders for same product
      const existingPendingOrder = await PurchaseOrder.findOne({
        supplierId: supplier._id,
        status: 'pending',
        'items.productId': product._id,
      });

      if (existingPendingOrder) continue;

      if (!supplierProductMap.has(supplier._id.toString())) {
        supplierProductMap.set(supplier._id.toString(), {
          supplier,
          products: [],
        });
      }
      supplierProductMap.get(supplier._id.toString()).products.push(product);
    }

    // Create one order per supplier
    for (const [, { supplier, products }] of supplierProductMap) {
      const items = products.map((p) => ({
        productId: p._id,
        productName: p.name,
        quantity: Math.max(1, p.minStockLevel * 2 - p.quantity), // Order to 2x minimum
        unitPrice: p.buyingPrice,
      }));

      const totalAmount = items.reduce((s, i) => s + i.quantity * i.unitPrice, 0);

      const order = await PurchaseOrder.create({
        supplierId: supplier._id,
        supplierName: supplier.name,
        items,
        totalAmount,
        isAutoGenerated: true,
        status: 'pending',
      });

      // Send email notification for the auto order
      try {
        await sendAutoOrderEmail(order, supplier);
        await PurchaseOrder.findByIdAndUpdate(order._id, {
          emailSent: true,
          emailSentAt: new Date(),
        });
        console.log(`📦 Auto order created & email sent for supplier: ${supplier.name}`);
      } catch (emailErr) {
        console.error(`Failed to send auto order email to ${supplier.name}:`, emailErr.message);
      }
    }
  } catch (error) {
    console.error('Low stock check error:', error.message);
  }
};

// ─── Expiry Check ─────────────────────────────────────────────────────────────

const checkExpiringProducts = async () => {
  console.log(`[${new Date().toISOString()}] Running expiry check...`);
  try {
    const today = new Date();
    const in30Days = new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000);

    const expiringProducts = await Product.find({
      isActive: true,
      expiryDate: { $gte: today, $lte: in30Days },
      expiryAlertSent: false,
    });

    if (!expiringProducts.length) {
      console.log('✅ No expiring products found.');
      return;
    }

    console.log(`⏰ Found ${expiringProducts.length} expiring product(s).`);

    // Enrich with daysUntilExpiry for the email template
    const productsWithDays = expiringProducts.map((p) => ({
      ...p.toObject(),
      daysUntilExpiry: Math.ceil((p.expiryDate - today) / (1000 * 60 * 60 * 24)),
    }));

    try {
      await sendExpiryAlert(productsWithDays);
      console.log(`📧 Expiry alert sent for ${expiringProducts.length} product(s).`);

      // Mark alert as sent
      await Product.updateMany(
        { _id: { $in: expiringProducts.map((p) => p._id) } },
        { expiryAlertSent: true }
      );
    } catch (emailErr) {
      console.error('Failed to send expiry email:', emailErr.message);
    }
  } catch (error) {
    console.error('Expiry check error:', error.message);
  }
};

// ─── Reset alert flags when stock is replenished ───────────────────────────

const resetAlertFlagsOnRestock = async (productId) => {
  try {
    const product = await Product.findById(productId);
    if (product && product.quantity > product.minStockLevel && product.lowStockAlertSent) {
      await Product.findByIdAndUpdate(productId, { lowStockAlertSent: false });
    }
  } catch (error) {
    console.error('Error resetting alert flag:', error.message);
  }
};

// ─── Scheduler Setup ─────────────────────────────────────────────────────────

const initScheduler = () => {
  const lowStockCron = process.env.LOW_STOCK_CRON || '0 8 * * *';   // Default: 8 AM daily
  const expiryCron = process.env.EXPIRY_CHECK_CRON || '0 7 * * *';  // Default: 7 AM daily

  cron.schedule(lowStockCron, checkLowStockAndAutoOrder, {
    timezone: 'Africa/Nairobi',
  });

  cron.schedule(expiryCron, checkExpiringProducts, {
    timezone: 'Africa/Nairobi',
  });

  console.log(`⏰ Scheduler initialized:`);
  console.log(`   Low stock check: ${lowStockCron}`);
  console.log(`   Expiry check:    ${expiryCron}`);
};

module.exports = {
  initScheduler,
  checkLowStockAndAutoOrder,
  checkExpiringProducts,
  resetAlertFlagsOnRestock,
};