import mongoose from 'mongoose';

const orderItemSchema = new mongoose.Schema({
  productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
  productName: String,
  quantity: Number,
  unitPrice: Number
});

const orderSchema = new mongoose.Schema({
  supplierId: { type: mongoose.Schema.Types.ObjectId, ref: 'Supplier', required: true },
  supplierName: String,
  items: [orderItemSchema],
  totalAmount: Number,
  status: { type: String, enum: ['pending', 'ordered', 'received', 'cancelled'], default: 'pending' },
  isAutoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

export default mongoose.model('Order', orderSchema);