const mongoose = require('mongoose');

const orderItemSchema = new mongoose.Schema(
  {
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product',
      required: true,
    },
    productName: { type: String, required: true },
    quantity: { type: Number, required: true, min: 1 },
    unitPrice: { type: Number, required: true, min: 0 },
  },
  { _id: false }
);

const purchaseOrderSchema = new mongoose.Schema(
  {
    supplierId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Supplier',
      required: true,
    },
    supplierName: {
      type: String,
      required: true,
    },
    items: {
      type: [orderItemSchema],
      required: true,
      validate: {
        validator: (v) => v.length > 0,
        message: 'Order must have at least one item',
      },
    },
    totalAmount: {
      type: Number,
      required: true,
      min: 0,
    },
    status: {
      type: String,
      enum: ['pending', 'ordered', 'received', 'cancelled'],
      default: 'pending',
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    notes: {
      type: String,
      trim: true,
    },
    // When status changed to 'ordered'
    orderedAt: { type: Date },
    // When status changed to 'received'
    receivedAt: { type: Date },
    // Email notification sent
    emailSent: { type: Boolean, default: false },
    emailSentAt: { type: Date },
  },
  {
    timestamps: true,
  }
);

// Auto-set timestamps on status change
purchaseOrderSchema.pre('save', function (next) {
  if (this.isModified('status')) {
    if (this.status === 'ordered' && !this.orderedAt) {
      this.orderedAt = new Date();
    }
    if (this.status === 'received' && !this.receivedAt) {
      this.receivedAt = new Date();
    }
  }
  next();
});

purchaseOrderSchema.index({ status: 1 });
purchaseOrderSchema.index({ supplierId: 1 });
purchaseOrderSchema.index({ isAutoGenerated: 1 });
purchaseOrderSchema.index({ createdAt: -1 });

module.exports = mongoose.model('PurchaseOrder', purchaseOrderSchema);